const EXERCISE_RECORD_REQUEST = 'EXERCISE_RECORD_REQUEST'
const EXERCISE_RECORD_SAVE = 'EXERCISE_RECORD_SAVE'
const EXERCISE_RECORD_SAVE_FAIL = 'EXERCISE_RECORD_SAVE_FAIL'
const EXERCISE_RECORD_GET = 'EXERCISE_RECORD_GET'
const EXERCISE_RECORD_GET_FAIL = 'EXERCISE_RECORD_GET_FAIL'
const EXERCISE_RECORD_DETAIL_REQUEST = 'EXERCISE_RECORD_DETAIL_REQUEST'
const EXERCISE_RECORD_DETAIL_GET = 'EXERCISE_RECORD_DETAIL_GET'
const EXERCISE_RECORD_DETAIL_GETFAIL = 'EXERCISE_RECORD_DETAIL_GETFAIL'

const HEALTH_RECORD_REQUEST = 'HEALTH_RECORD_REQUEST'
const HEALTH_RECORD_LIST_REQUEST = 'HEALTH_RECORD_LIST_REQUEST'
const HEALTH_RECORD_SAVE = 'HEALTH_RECORD_SAVE'
const HEALTH_RECORD_SAVE_FAIL = 'HEALTH_RECORD_SAVE_FAIL'
const HEALTH_RECORD_DETAIL_REQUEST = 'HEALTH_RECORD_DETAIL_REQUEST'
const HEALTH_RECORD_DETAIL_FAIL = 'HEALTH_RECORD_DETAIL_FAIL'
const HEALTH_RECORD_GET = 'HEALTH_RECORD_GET'
const HEALTH_RECORD_GET_FAIL = 'HEALTH_RECORD_GET_FAIL'
const HEALTH_RECORD_SAVE_RESET = 'HEALTH_RECORD_SAVE_RESET'

export {
    HEALTH_RECORD_REQUEST, HEALTH_RECORD_SAVE, HEALTH_RECORD_SAVE_FAIL, HEALTH_RECORD_GET, HEALTH_RECORD_GET_FAIL,
    HEALTH_RECORD_LIST_REQUEST,HEALTH_RECORD_DETAIL_REQUEST, HEALTH_RECORD_DETAIL_FAIL, HEALTH_RECORD_SAVE_RESET,
    EXERCISE_RECORD_REQUEST, EXERCISE_RECORD_SAVE, EXERCISE_RECORD_SAVE_FAIL,
    EXERCISE_RECORD_GET, EXERCISE_RECORD_GET_FAIL, 
    EXERCISE_RECORD_DETAIL_REQUEST, EXERCISE_RECORD_DETAIL_GET, EXERCISE_RECORD_DETAIL_GETFAIL
}
